version: '2'
services:
    books-app:
        image: books
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://books-mysql:3306/books?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=books-elasticsearch:9300
        ports:
            - 8080:8080
    books-mysql:
        extends:
            file: mysql.yml
            service: books-mysql
    books-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: books-elasticsearch
